<?php



/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link http://docs.lion.org/dev/Languages/AMOS}) using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package    install
 * @subpackage lang
 * @copyright  2015 Pooya Saeedi
 */

defined('LION_INTERNAL') || die();

$string['clianswerno'] = 'n';
$string['cliansweryes'] = 'y';
$string['cliincorrectvalueerror'] = 'Lỗi, giá trị không đúng "{$a->value}" for "{$a->option}"';
$string['cliincorrectvalueretry'] = 'Giá trị không đúng, vui lòng thử lại';
$string['clitypevalue'] = 'nhập giá trị';
$string['clitypevaluedefault'] = 'nhập giá trị, nhấn phím Enter để dùng giá trị mặc định ({$a})';
$string['cliunknowoption'] = 'Lựa chọn chưa được nhận diện:
  {$a}
Vui lòng sử dụng lựa chọn --help.';
$string['cliyesnoprompt'] = 'nhập y (có) hay n (không)';
$string['environmentrequireinstall'] = 'cần phải được cài hay kích hoạt.';
$string['environmentrequireversion'] = 'Cần phiên bản {$a->needed} trong khi bạn đang dùng {$a->current}';
