<?php


/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically  using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * 
 */

defined('LION_INTERNAL') || die();

$string['cliincorrectvalueerror'] = 'Kosa, thamani isiyo sahihi "{$a-> thamani}" kwa "{$a-> chaguo}"';
$string['cliincorrectvalueretry'] = 'Thamani isiyo sahihi, tafadhali Jaribu tena';
$string['clitypevalue'] = 'Andika nambari au herufi';
$string['clitypevaluedefault'] = 'Andika nambari, kisha bonyeza Enter ili kutumia nambari uliyopewa ({$a})';
$string['cliyesnoprompt'] = 'Kuandika y (maana ndiyo) au n (la)';
