<?php


/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically  using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * 
 */

defined('LION_INTERNAL') || die();

$string['clianswerno'] = 'n';
$string['cliansweryes'] = 'y';
$string['cliincorrectvalueerror'] = 'Error, valor incorrecte « {$a->value} » per lo paramètre « {$a->option} »';
$string['cliincorrectvalueretry'] = 'Valor incorrecte, veuillez réessayer';
$string['clitypevalue'] = 'tipe valor';
$string['clitypevaluedefault'] = 'tipe valor, tapez Entrée per utilizar la valor per defaut ({$a})';
$string['cliunknowoption'] = 'Options non reconnues :
 {$a}.
Utilisez l\'option --help.';
$string['cliyesnoprompt'] = 'Tapez y (pour oui) o n (pour non)';
$string['environmentrequireinstall'] = 'doit être installé e activé';
$string['environmentrequireversion'] = 'la version {$a->needed} es requise ; vous utilisez actualament la version {$a->current}';
