<?php


/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically  using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * 
 */

defined('LION_INTERNAL') || die();

$string['clianswerno'] = 'na';
$string['cliansweryes'] = 'gie';
$string['cliincorrectvalueretry'] = 'Quei ei buca correct, emprova aunc inagada';
$string['clitypevalue'] = 'Tipar valur (value)';
$string['cliyesnoprompt'] = 'Tippar gie ni na';
