<?php



/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link http://docs.lion.org/dev/Languages/AMOS}) using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package    install
 * @subpackage lang
 * @copyright  2015 Pooya Saeedi
 */

defined('LION_INTERNAL') || die();

$string['admindirname'] = 'అడ్మిన్ డైరెక్టరీ';
$string['availablelangs'] = 'అందుబాటులో ఉన్న భాషల జాబితా';
$string['chooselanguagehead'] = 'భాషను ఎంచుకోండి';
$string['databasehost'] = 'డేటాబేసు హోస్టు';
$string['databasename'] = 'డేటాబేసు పేరు';
$string['databasetypehead'] = 'డేటాబేస్ డ్రైవర్ ఎంచుకోండి';
$string['dataroot'] = 'డేటా డైరెక్టరీ';
$string['datarootpermission'] = 'డేటా డైరెక్టరీల అనుమతి';
$string['dbprefix'] = 'టేబుళ్ళ ఆదిపదం (ప్రిఫిక్స్)';
$string['dirroot'] = 'Lion డైరెక్టరీ';
$string['environmenthead'] = 'మీ ఎన్విరాన్మెంటును పరిశీలిస్తున్నాం ...';
$string['installation'] = 'సంస్థాపన';
$string['paths'] = 'మార్గాలు';
$string['pathswrongadmindir'] = 'అడ్మిన్ డైరెక్టరీ అసలు లేదు';
$string['wwwroot'] = 'వెబ్ చిరునామా';
