<?php



/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link http://docs.lion.org/dev/Languages/AMOS}) using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package    install
 * @subpackage lang
 * @copyright  2015 Pooya Saeedi
 */

defined('LION_INTERNAL') || die();

$string['cannotcreatelangdir'] = 'Не може да се креира lang директориумот.';
$string['cannotcreatetempdir'] = 'Не може да се креира temp директориумот.';
$string['cannotdownloadcomponents'] = 'Не може да се преземат компонентите.';
$string['cannotdownloadzipfile'] = 'Не може да се преземи ZIP датотеката.';
$string['cannotfindcomponent'] = 'Не може да се најде компонентата.';
$string['cannotsavemd5file'] = 'Не може да се сними md5 датотеката.';
$string['cannotsavezipfile'] = 'Не може да се сними ZIP датотеката.';
$string['cannotunzipfile'] = 'Не може да се отпакува датотеката.';
$string['componentisuptodate'] = 'Компонентата е од последната верзија';
$string['downloadedfilecheckfailed'] = 'Проверката на преземената датотека не заврши успешно.';
$string['invalidmd5'] = 'невалидна md5';
$string['missingrequiredfield'] = 'Некои задолжителни полиња недостасуваат';
$string['wrongdestpath'] = 'Погрешна дестинација.';
$string['wrongsourcebase'] = 'Погрешна изворна адреса.';
$string['wrongzipfilename'] = 'Погрешна ZIP датотека.';
