<?php



/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link http://docs.lion.org/dev/Languages/AMOS}) using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package    install
 * @subpackage lang
 * @copyright  2015 Pooya Saeedi
 */

defined('LION_INTERNAL') || die();

$string['cannotcreatelangdir'] = 'lang хавтсыг үүсгэх боломжгүй.';
$string['cannotcreatetempdir'] = 'temp  директор үүсгэж чадахгүй байна';
$string['cannotdownloadcomponents'] = 'Компонент татаж чадахгүй байна.';
$string['cannotdownloadzipfile'] = 'Zip файл татаж чадахгүй байна';
$string['cannotfindcomponent'] = 'Компонент олж чадахгүй байна';
$string['cannotsavemd5file'] = 'md5  файл хадгалж чадахгүй байна.';
$string['cannotsavezipfile'] = 'Zip  файл хадгалж чадахгүй байна.';
$string['cannotunzipfile'] = 'Файл unzip хийж чадахгүй байна.';
$string['componentisuptodate'] = 'Компонент сүүлийн хувилбар байна.';
$string['downloadedfilecheckfailed'] = 'Татаж авсан файлыг шалгах үйл ажиллагаа бүтсэнгүй.';
$string['invalidmd5'] = 'Буруу md5';
$string['missingrequiredfield'] = 'Зарим шаардлагатай талбар орхигдсон байна.';
$string['wrongdestpath'] = 'Буруу очих зам байна. .';
$string['wrongsourcebase'] = 'Буруу хаягийн мэдээлэл байна.';
$string['wrongzipfilename'] = 'Буруу архивласан файлын нэр байна.';
