<?php


/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically  using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * 
 */

defined('LION_INTERNAL') || die();

$string['clianswerno'] = 'N';
$string['cliansweryes'] = 'A';
$string['cliincorrectvalueerror'] = 'Chyba, nesprávna hodnota "{$a->value}" for "{$a->option}"';
$string['cliincorrectvalueretry'] = 'Nesprávna hodnota, prosím skúste znova';
$string['clitypevalue'] = 'Vložte hodnotu';
$string['clitypevaluedefault'] = 'Vložte hodnotu a stlačte klávesu Enter pre použitie nastavenej hodnoty ({$a})';
$string['cliunknowoption'] = 'Nerozoznané voľby: {$a}
Prosím, použite možnosť --help.';
$string['cliyesnoprompt'] = 'Zvolte A (Áno) alebo N (Nie)';
$string['environmentrequireinstall'] = 'vyžadovaný komponent';
$string['environmentrequireversion'] = 'vyžadovaná je verzia {$a->needed}, teraz používate verziu {$a->current}';
