<?php



/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link http://docs.lion.org/dev/Languages/AMOS}) using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package    install
 * @subpackage lang
 * @copyright  2015 Pooya Saeedi
 */

defined('LION_INTERNAL') || die();

$string['cannotcreatelangdir'] = 'Kāore i taea te whaiaronga reo.';
$string['cannotcreatetempdir'] = 'Kāore i taea te whaiaronga rangitaki.';
$string['cannotdownloadcomponents'] = 'Kāore i taea ngā wae te tikiake.';
$string['cannotdownloadzipfile'] = 'Kāore i taea te kōnae KŌTUI te tikiake.';
$string['cannotfindcomponent'] = 'Kāore i taea te wae te kite.';
$string['cannotsavemd5file'] = 'Kāore i taea te kōnae md5 te tiaki.';
$string['cannotsavezipfile'] = 'Kāore i taea te kōnae KŌTUI te tiaki.';
$string['cannotunzipfile'] = 'Kāore i taea te kōnae te whewhera.';
$string['componentisuptodate'] = 'Tika tonu te wae ki te rā';
$string['downloadedfilecheckfailed'] = 'I rahua te takinga o te kōnae i tikina ake';
$string['invalidmd5'] = 'md5 muhu';
$string['missingrequiredfield'] = 'E ngaro ana tētahi āpure e hiahiatia ana';
$string['remotedownloaderror'] = 'Tiki ake o to mōtete ki te tūmau i hinga, manatoko koa i ō tautuhinga takawaenga, PHP cURL  toronga kei te tino tutohua.<br /><br /> Me tiki ake koe i te <a href="{$a->url}">{$a->url}</a> kōnae ā-ringa, tāruangia ki te  "{$a->dest}"  i tō tūmau me te pōutāpeta ki reira.';
$string['wrongdestpath'] = 'Ehara tēnei ara ūnga i te tika';
$string['wrongsourcebase'] = 'Ehara tēnei tumu URL pūtake i te tika';
$string['wrongzipfilename'] = 'Ehara tēnei ingoakōnae ZIP i te tika';
