<?php


/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link http://docs.lion.org/dev/Languages/AMOS}) using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * 
 */

defined('LION_INTERNAL') || die();

$string['cannotcreatelangdir'] = 'Nevar izveidot valodas direktoriju';
$string['cannotcreatetempdir'] = 'Nevar izveidot pagaidu direktoriju';
$string['cannotdownloadcomponents'] = 'Nevar lejupielādēt komponentus';
$string['cannotdownloadzipfile'] = 'Nevar lejupielādēt ZIP failu';
$string['cannotfindcomponent'] = 'Nevar atrast komponentu';
$string['cannotsavemd5file'] = 'Nevar saglabāt md5 failu';
$string['cannotsavezipfile'] = 'Nevar saglabāt ZIP failu';
$string['cannotunzipfile'] = 'Nevar atzipot failu';
$string['componentisuptodate'] = 'Komponents atbilst visjaunākajai versijai.';
$string['downloadedfilecheckfailed'] = 'Lejupielādētā faila pārbaudes rezultāts nesekmīgs.';
$string['invalidmd5'] = 'Nederīgs md5';
$string['missingrequiredfield'] = 'Trūkst kāda nepieciešamā lauka';
$string['wrongdestpath'] = 'Nepareizs mērķa ceļš.';
$string['wrongsourcebase'] = 'Nepareiza avota URL bāze.';
$string['wrongzipfilename'] = 'Nepareizs ZIP faila nosaukums.';
