<?php


/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link http://docs.lion.org/dev/Languages/AMOS}) using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * 
 */

defined('LION_INTERNAL') || die();

$string['clianswerno'] = 'не';
$string['cliansweryes'] = 'ҳа';
$string['cliincorrectvalueerror'] = 'Хато, нишондиҳандаи нодурусти "{$a->value}" барои "{$a->option}"';
$string['cliincorrectvalueretry'] = 'Нишондиҳандаи нодуруст, илтимос, аз нав кӯшиш карда бинед';
$string['clitypevalue'] = 'Нишондиҳандаро ворид намоед';
$string['clitypevaluedefault'] = 'Нишондиҳандаро ворид намоед, Enter-ро барои истифодаи нишондиҳанда аз рӯи хомӯшӣ ({$a}) зер кунед';
$string['cliunknowoption'] = 'Параметрҳои шинохтанашуда:
  {$a}
Илтимос, аз параметри --help истифода баред';
$string['cliyesnoprompt'] = 'Ҳарфҳои y (яъне Ҳа) ё n (яъне Не)';
$string['environmentrequireinstall'] = 'Ҷойгир карда ба кор андохтан лозим аст';
$string['environmentrequireversion'] = 'Версияи {$a->needed} лозим аст, Шумо версияи {$a->current} -ро истифода бурда истодаед';
