<?php


/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link http://docs.lion.org/dev/Languages/AMOS}) using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * 
 */

defined('LION_INTERNAL') || die();

$string['cannotcreatelangdir'] = 'Феҳристи забонро бунёд кардан муасар нашуда истодааст';
$string['cannotcreatetempdir'] = 'Феҳристи муваққатӣ бунёд кардан нашуда истодааст';
$string['cannotdownloadcomponents'] = 'Қисматҳоро бор кардан ғайриимкон аст.';
$string['cannotdownloadzipfile'] = 'ZIP-файлро бор кардан муяссар нашуд';
$string['cannotfindcomponent'] = 'Қисматро ёфтан муяссар нашуд';
$string['cannotsavemd5file'] = 'MD5-файлро маҳфуз доштан муяссар нашуд';
$string['cannotsavezipfile'] = 'ZIP-файлро маҳфуз доштан муяссар нашуд';
$string['cannotunzipfile'] = 'Файлро кушодан муяссар нашуд';
$string['componentisuptodate'] = 'Қисмат ба навсозӣ эҳтиёҷ надорад';
$string['downloadedfilecheckfailed'] = 'Хатои тафтиши файли боркардашуда';
$string['invalidmd5'] = 'md5-и нодуруст';
$string['missingrequiredfield'] = 'Баъзе майдонҳои ҳатмӣ нестанд';
$string['remotedownloaderror'] = 'Қисматро ба сервер бор кардан муяссар нашуд, танзимҳои прокси-серверро тафтиш кунед, бо исрор тавсия дода мешавад, ки васеъкунии cURL-и забони PHP ҷойгир карда шавад.<br /> <br />Шумо бояд файлро аз рӯи истиноди <a href="{$a->url}">{$a->url}</a> дастӣ бор кунед, онро ба папкаи "{$a->dest}" дар сервери худ нусхабардорӣ намоед ва дар он ҷо онро кушоед.';
$string['wrongdestpath'] = 'Роҳи хатои таъйинкунӣ';
$string['wrongsourcebase'] = 'Адреси нодурусти сарчашма';
$string['wrongzipfilename'] = 'Номи нодурусти ZIP-файл';
