<?php


/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically  using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * 
 */

defined('LION_INTERNAL') || die();

$string['environmentrequireinstall'] = 'ස්ථාපනයට/ක්‍රියාත්මක කිරීමට අවශ්‍යයි';
$string['environmentrequireversion'] = '{$a->needed} අනුවාදය අවශ්‍ය කරන අතර දැනට ඔබ භා‍විතාකරන්නේ {$a->current} අනුවාදයයි';
