<?php


/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically  using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * 
 */

defined('LION_INTERNAL') || die();

$string['cannotcreatelangdir'] = 'lang ඩිරෙක්ටරිය සෑදීය නොහැක';
$string['cannotcreatetempdir'] = 'temp ඩිරෙක්ටරිය සෑදීය නොහැක';
$string['cannotdownloadcomponents'] = 'සංරචක බාගත කළ නොහැක';
$string['cannotdownloadzipfile'] = 'zip ගොනු බාගත කල නොහැක';
$string['cannotfindcomponent'] = 'සංරචක සොයාගත නොහැක';
$string['cannotsavemd5file'] = 'md5 ගොනුව සුරක්ෂිත කල නොහැක';
$string['cannotsavezipfile'] = 'zip ගොනුව සුරක්ෂිත කල නොහැක';
$string['cannotunzipfile'] = 'ගොනුව අසම්පීඩිත කල නොහැක';
$string['componentisuptodate'] = 'සංරචකය යාවත්කාලීන වී ඇත';
$string['downloadedfilecheckfailed'] = 'බාගත කරන ලද ගොනු පරික්ෂාව නොහැකිවිය';
$string['invalidmd5'] = 'අවලංගු md5';
$string['missingrequiredfield'] = 'අත්‍යවශ්‍ය ක්ෂේත්‍ර කිහිපයක් අස්ථානගතවී ඇත';
$string['wrongdestpath'] = 'වැරදි ගමනාන්ත පථයකි';
$string['wrongsourcebase'] = 'වැරදි මූලාශ්‍ර URL පදනමකි';
$string['wrongzipfilename'] = 'වැරදි ZIP ගොනු නාමයකි';
