<?php



/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link http://docs.lion.org/dev/Languages/AMOS}) using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package    install
 * @subpackage lang
 * @copyright  2015 Pooya Saeedi
 */

defined('LION_INTERNAL') || die();

$string['admindirname'] = 'admin ඩිරෙක්ටරිය';
$string['availablelangs'] = 'පවතින භාෂා ලයිස්තුව';
$string['chooselanguagehead'] = 'භාෂාවක් තෝරාගන්න';
$string['databasehost'] = 'දත්තගබඩා ධාරකය';
$string['databasename'] = 'දත්තගබඩා නම:';
$string['dataroot'] = 'දත්ත ඩිරෙක්ටරිය';
$string['dbprefix'] = 'වගු උපසර්ගය';
$string['dirroot'] = 'මූඩ්ල් ඩිරෙක්ටරිය';
$string['environmenthead'] = 'ඔබගේ පාරිසරිකය පරීක්ෂා කිරීම';
$string['errorsinenvironment'] = 'පරිසරයේ දෝෂයකි!';
$string['installation'] = 'පිහිටුවීම';
$string['phpversion'] = 'PHP සංස්කරණය';
$string['welcomep10'] = '{$a->installername} ({$a->installerversion})';
$string['wwwroot'] = 'අන්තර්ජාල ලිපිනය';
