<?php


/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link http://docs.lion.org/dev/Languages/AMOS}) using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * 
 */

defined('LION_INTERNAL') || die();

$string['cliincorrectvalueerror'] = 'பிழை இருக்கிறது. இந்த "{$a->option}"-க்கு இந்த "{$a->value}" தவறான மதிப்பு.';
$string['cliincorrectvalueretry'] = 'தவறான மதிப்பு. தயவு செய்து மீண்டும் முயற்சிக்கவும்';
$string['clitypevalue'] = 'மதிப்பை உள்ளீடு செய்யவும்';
$string['clitypevaluedefault'] = 'மதிப்பை உள்ளீடு செய்யவும், கொடா மதிப்பான ({$a})-ஐ பயன்படுத்த Enter-ஐ அழுத்தவும்';
$string['cliunknowoption'] = 'அங்கீகரிக்கப்படாத விருப்பங்கள்:
 {$a}
தயவு செய்து --help தேர்வை பயன்படுத்தவும்.';
$string['cliyesnoprompt'] = 'தட்டச்சு செய்யவும். ஆம் என்றால் y (அல்லது) இல்லை என்றால் n';
$string['environmentrequireinstall'] = 'is required to be installed/enabled.';
$string['environmentrequireversion'] = 'version {$a->needed} is required and you are running {$a->current}';
