<?php


/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically  using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * 
 */

defined('LION_INTERNAL') || die();

$string['welcomep50'] = 'The use of all the applications in this package is governed by their respective licenses. The complete <strong>{$a->installername}</strong> package is <a href="http://www.opensource.org/docs/definition_plain.html">open source</a> and is distributed under the <a href="http://www.gnu.org/copyleft/gpl.html">GPL</a> license.';
