<?php



/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link http://docs.lion.org/dev/Languages/AMOS}) using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package    install
 * @subpackage lang
 * @copyright  2015 Pooya Saeedi
 */

defined('LION_INTERNAL') || die();

$string['cannotcreatelangdir'] = 'lang dir બનાવી શકાતી નથી.';
$string['cannotcreatetempdir'] = 'temp dir બનાવી શકાતી નથી.';
$string['cannotdownloadcomponents'] = 'કમ્પોનન્ટ્સ ડાઊનલોડ કરી શકાતા નથી.';
$string['cannotdownloadzipfile'] = 'ઝિપ ફાઈલ ડાઊનલોડ કરી શકાતી નથી.';
$string['cannotfindcomponent'] = 'કમ્પોનન્ટ શોધી શકાતા નથી';
$string['cannotsavemd5file'] = 'md5 file સેવ કરી શકાતી નથી.';
$string['cannotsavezipfile'] = 'ZIP file સેવ કરી શકાતી નથી.';
$string['cannotunzipfile'] = 'ફાઈલને અનઝિપ કરી શકાતી નથી';
$string['componentisuptodate'] = 'કમ્પોનન્ટ અપ ડેઈટ છે.';
$string['downloadedfilecheckfailed'] = 'ડાઊનલોડ કરેલ ફાઈલનું ચેક નિષ્ફળ રહ્યું';
$string['invalidmd5'] = 'અમન્ય md5';
$string['missingrequiredfield'] = 'કેટલાક જરૂરી ફિલ્ડ ગુમ છે';
$string['wrongdestpath'] = 'ખોટો ડેસ્ટીનેશન પાથ.';
$string['wrongzipfilename'] = 'ખોટું ઝિપ ફાઈલ નામ.';
