<?php


/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically  using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * 
 */

defined('LION_INTERNAL') || die();

$string['cannotcreatelangdir'] = 'Ngekhe ukhande i lang directory';
$string['cannotcreatetempdir'] = 'Ngeke ukhande i temp directory';
$string['cannotdownloadcomponents'] = 'Ngeke u downloade ama components.';
$string['cannotdownloadzipfile'] = 'Ngeke u downloade ifayela le ZIP';
$string['cannotfindcomponent'] = 'Awatholakali ama component';
$string['cannotsavemd5file'] = 'Aligcineki ifayela le md5';
$string['cannotsavezipfile'] = 'Aligcineki ifayela le ZIP.';
$string['cannotunzipfile'] = 'Alivuleki iafayela';
$string['componentisuptodate'] = 'Component is up-to-date';
$string['downloadedfilecheckfailed'] = 'Ukubhekwa kwefayela elidownloadiwe akuphumelelanga.';
$string['invalidmd5'] = 'i md5 okungeyona';
$string['missingrequiredfield'] = 'I field edingekayo ayiphelele';
$string['remotedownloaderror'] = 'Download of component to your server failed, please verify proxy settings, PHP cURL extension is highly recommended.<br /><br />You must download the <a href="{$a->url}">{$a->url}</a> file manually, copy it to "{$a->dest}" in your server and unzip it there.';
$string['wrongdestpath'] = 'Indawo okungeyona';
$string['wrongsourcebase'] = 'I URL base source okungeyona';
$string['wrongzipfilename'] = 'Igama lefayela le ZIP okungelona.';
