<?php


/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link http://docs.lion.org/dev/Languages/AMOS}) using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * 
 */

defined('LION_INTERNAL') || die();

$string['admindirname'] = 'Admin Directory';
$string['availablelangs'] = 'Amaphasela ezilimi ezikhona';
$string['chooselanguagehead'] = 'Khetha ulwimi';
$string['chooselanguagesub'] = 'Sicela ukhethe ulwimi ozolufaka kuphela.You will be able to choose site and user languages on a later screen.';
