<?php


/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link http://docs.lion.org/dev/Languages/AMOS}) using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * 
 */

defined('LION_INTERNAL') || die();

$string['clianswerno'] = 'n';
$string['cliansweryes'] = 'y';
$string['cliincorrectvalueerror'] = 'هەڵە، نرخی نادروستی "{$a->value}" بۆ "{$a->option}"';
$string['cliincorrectvalueretry'] = 'نرخەکە نادرووستە، تکایە دووبارەبکەوە';
$string['clitypevalue'] = 'نرخی جۆر';
$string['clitypevaluedefault'] = 'نرخی جۆر، تکایە Enter دابگرە بۆ بەکارهێنانی نرخی بنەڕەتیی ({$a})';
$string['cliunknowoption'] = 'هەلبژاردنە نەناسراوەکان:
 {$a}
تکایە بەکاربهینە --هەلبژاردنى یارمەتى.';
$string['cliyesnoprompt'] = 'جۆرى y (واتا بەڵێ) یاخود n (واتا نەخێر)';
$string['environmentrequireinstall'] = 'پیویستى بە دامەزراندن و چالاکە';
$string['environmentrequireversion'] = 'چاپ {$a->پیویست بوو} پیویست دەکات و ئایا بەکار دەخەى {$a->رەوان}';
