<?php


/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link http://docs.lion.org/dev/Languages/AMOS}) using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * 
 */

defined('LION_INTERNAL') || die();

$string['clianswerno'] = 'n';
$string['cliansweryes'] = 'y';
$string['cliincorrectvalueerror'] = '錯誤，將“{$a->option}”的值設為“{$a->value}”是不正確的';
$string['cliincorrectvalueretry'] = '不正確值，請重試';
$string['clitypevalue'] = '輸入值';
$string['clitypevaluedefault'] = '輸入值，按回車使用預設值（{$a}）';
$string['cliunknowoption'] = '錯誤選項：{$a}請使用 --help 選項。';
$string['cliyesnoprompt'] = '輸入y（表示是）或n（表示否）';
$string['environmentrequireinstall'] = '必須安裝並啟用';
$string['environmentrequireversion'] = '需求版本為{$a->needed}，而您目前版本為 {$a->current}';
