<?php


/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link http://docs.lion.org/dev/Languages/AMOS}) using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * 
 */

defined('LION_INTERNAL') || die();

$string['clianswerno'] = 'n';
$string['cliansweryes'] = 'j';
$string['cliincorrectvalueerror'] = 'Villa, ótækt gildi "{$a->value}" fyrir "{$a->option}"';
$string['cliincorrectvalueretry'] = 'Rangt gildi, vinsamlegast reyndu aftur';
$string['clitypevalue'] = 'Sláðu inn gildi';
$string['clitypevaluedefault'] = 'Sláðu inn gildi, sláðu á Enter hnappinn á lyklaborðinu til að nota sjálfgefið gildi ({$a})';
$string['cliunknowoption'] = 'Óþekktir valkostir:
  {$a}
Vinsamlegast notaðu --help valkostinn.';
$string['cliyesnoprompt'] = 'skráðu y (þýðir já) eða n (þýðir nei)';
$string['environmentrequireinstall'] = 'verður að vera uppsett og virkjað';
$string['environmentrequireversion'] = 'krafist er útgáfu {$a->needed} en þú notast við útgáfu {$a->current}';
