<?php



/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link http://docs.lion.org/dev/Languages/AMOS}) using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package    install
 * @subpackage lang
 * @copyright  2015 Pooya Saeedi
 */

defined('LION_INTERNAL') || die();

$string['cannotcreatelangdir'] = 'Get ekki myndað lang skráarsafnið';
$string['cannotcreatetempdir'] = 'Get ekki myndað tímabundið skráarsafn';
$string['cannotdownloadcomponents'] = 'Get ekki sótt viðbótareiningar';
$string['cannotdownloadzipfile'] = 'Get ekki sótt ZIP skrá';
$string['cannotfindcomponent'] = 'Finn ekki viðbótareiningu';
$string['cannotsavemd5file'] = 'Get ekki vistað md5 skrá';
$string['cannotsavezipfile'] = 'Get ekki vistað ZIP skrá';
$string['cannotunzipfile'] = 'Get ekki afþjappað skrá';
$string['invalidmd5'] = 'Ótækt md5';
$string['missingrequiredfield'] = 'Einhverjir reitir eru enn óútfylltir';
$string['wrongzipfilename'] = 'Rang skráarheiti á ZIP skrá.';
