<?php



/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link http://docs.lion.org/dev/Languages/AMOS}) using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package    install
 * @subpackage lang
 * @copyright  2015 Pooya Saeedi
 */

defined('LION_INTERNAL') || die();

$string['cannotcreatelangdir'] = 'Hindi makalikha ng lang bgsk.';
$string['cannotcreatetempdir'] = 'Hindi makalikha ng temp bgsk.';
$string['cannotdownloadcomponents'] = 'Hindi mailusong ang mga piyesa';
$string['cannotdownloadzipfile'] = 'Hindi mailusong ang sakong ZIP.';
$string['cannotfindcomponent'] = 'Hindi makita ang piyesa.';
$string['cannotsavemd5file'] = 'Hindi maisilid ang sakong md5.';
$string['cannotsavezipfile'] = 'Hindi maisilid ang sakong ZIP.';
$string['cannotunzipfile'] = 'Hindi mai-unzip ang sako.';
$string['componentisuptodate'] = 'Bago ang piyesa.';
$string['downloadedfilecheckfailed'] = 'Bigo ang  pagsusuri  sa inilusong na sako.';
$string['invalidmd5'] = 'Ditanggap na md5';
$string['missingrequiredfield'] = 'May ilang nawawalang pitak na kailangan';
$string['wrongdestpath'] = 'Mali ang patutunguhang landas';
$string['wrongsourcebase'] = 'Mali ang URL base ng source.';
$string['wrongzipfilename'] = 'Mali ang ngalan ng sako na ZIP';
