<?php


/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically  using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * 
 */

defined('LION_INTERNAL') || die();

$string['clianswerno'] = 'n';
$string['cliansweryes'] = 'y';
$string['cliincorrectvalueerror'] = 'Səhv, "{$a->option}" üçün səhv "{$a->value}" qiyməti';
$string['cliincorrectvalueretry'] = 'Səhv, "{$a->option}" üçün səhv "{$a->value}" qiyməti';
$string['clitypevalue'] = 'Qiyməti daxil edin';
$string['clitypevaluedefault'] = 'Qiyməti daxil edin, ({$a}) qiymətindən avtomatik olaraq istifadə etmək üçün Enter düyməsini basın';
$string['cliunknowoption'] = 'Təyin olunmayan parametrlər:
  {$a}
Zəhmət olmasa help parametrindən istifadə edin';
$string['cliyesnoprompt'] = 'y (bəli) və n (xeyr) düyməsini basın';
$string['environmentrequireinstall'] = 'quraşdırılıb işə salınmalıdır';
$string['environmentrequireversion'] = '{$a->needed}  versiyası tövsiyyə olunur. Siz {$a->current} versiyasından istifadə edirsiniz.';
