<?php



/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link http://docs.lion.org/dev/Languages/AMOS}) using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package    install
 * @subpackage lang
 * @copyright  2015 Pooya Saeedi
 */

defined('LION_INTERNAL') || die();

$string['cannotcreatedboninstall'] = '<p>Methu creu y gronfa ddata.</p> <p>Dydy’r gronfa ddata benodedig ddim yn bodoli a does gan y defnyddiwr dan sylw ddim hawl i greu cronfa ddata.</p> <p>Dylai gweinyddwr y safle wirio ffurfweddu cronfeydd data.</p>';
$string['cannotcreatelangdir'] = 'Does dim modd creu cyfeiriadur iaith';
$string['cannotcreatetempdir'] = 'Does dim modd creu cyfeiriadur dros dro';
$string['cannotdownloadcomponents'] = 'Does dim modd llwytho cydrannau i lawr';
$string['cannotdownloadzipfile'] = 'Does dim modd llwytho ffeil ZIP i lawr';
$string['cannotfindcomponent'] = 'Does dim modd canfod cydran';
$string['cannotsavemd5file'] = 'Does dim modd cadw ffeil md5';
$string['cannotsavezipfile'] = 'Does dim modd cadw ffeil ZIP';
$string['cannotunzipfile'] = 'Does dim modd dadzipio\'r ffeil';
$string['componentisuptodate'] = 'Mae\'r gydran wedi\'i diweddaru';
$string['dmlexceptiononinstall'] = '<p>Roed gwall cronfa ddata [{$a->errorcode}].<br />{$a->debuginfo}</p>';
$string['downloadedfilecheckfailed'] = 'Heb lwyddo i wirio\'r ffeil a lwythwyd i lawr';
$string['invalidmd5'] = 'Roedd y newidyn gwirio yn anghywir - rhowch gynnig arall arni';
$string['missingrequiredfield'] = 'Mae maes gofynnol ar goll';
$string['remotedownloaderror'] = 'Wedi methu llwytho cydran ar eich gweinydd, gwiriwch osodiadau\'r dirprwy, argymhellir yr estyniad PHP cURL yn gryf.<br /><br />Mae\'n rhaid i chi lwytho\'r ffeil <a href="{$a->url}">{$a->url}</a> eich hun, ei chopïo i "{$a->dest}" ar eich gweinydd, a\'i dad-zipio yno.';
$string['wrongdestpath'] = 'Llwybr cyrchfan anghywir';
$string['wrongsourcebase'] = 'Bôn URL ffynhonnell anghywir';
$string['wrongzipfilename'] = 'Enw ffeil ZIP anghywir';
