<?php


/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically  using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * 
 */

defined('LION_INTERNAL') || die();

$string['clianswerno'] = 'n';
$string['cliansweryes'] = 'y';
$string['cliincorrectvalueerror'] = '错误，将“{$a->option}”的值设为“{$a->value}”是不正确的';
$string['cliincorrectvalueretry'] = '不正确的值，请重试';
$string['clitypevalue'] = '输入值';
$string['clitypevaluedefault'] = '输入值，按回车使用缺省值（{$a}）';
$string['cliunknowoption'] = '未识别的选项：
{$a}
请使用 --help 选项。';
$string['cliyesnoprompt'] = '输入y（表示是）或n（表示否）';
$string['environmentrequireinstall'] = '必须安装并启用';
$string['environmentrequireversion'] = '需要 {$a->needed} 版本，而您的是 {$a->current}';
