<?php



/**
 * An oauth2 redirection endpoint which can be used for an application:
 * http://tools.ietf.org/html/draft-ietf-oauth-v2-26#section-3.1.2
 *
 * This is used because some oauth servers will not allow a redirect urls
 * with get params (like repository callback) and that needs to be called
 * using the state param.
 *
 * @package    core
 * @subpackage admin
 * @copyright  2015 Pooya Saeedi
 */

require_once(dirname(dirname(__FILE__)).'/config.php');

// The authorization code generated by the authorization server.
$code = required_param('code', PARAM_RAW);
// The state parameter we've given (used in lion as a redirect url).
$state = required_param('state', PARAM_LOCALURL);

$redirecturl = new lion_url($state);
$params = $redirecturl->params();

if (isset($params['sesskey']) and confirm_sesskey($params['sesskey'])) {
    $redirecturl->param('oauth2code', $code);
    redirect($redirecturl);
} else {
    print_error('invalidsesskey');
}
