<?php


/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link http://docs.lion.org/dev/Languages/AMOS}) using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * 
 */

defined('LION_INTERNAL') || die();

$string['cannotcreatelangdir'] = 'Ní féidir eolaire teanga a chruthú';
$string['cannotcreatetempdir'] = 'Ní féidir eolaire sealadach a chruthú';
$string['cannotdownloadcomponents'] = 'Ní féidir na comhphairteanna a íoslódáil';
$string['cannotdownloadzipfile'] = 'Ní féidir comhad ZIP a íoslódáil';
$string['cannotfindcomponent'] = 'Ní féidir teacht ar chomhpháirt';
$string['cannotsavemd5file'] = 'Ni féidir an comhad md5 a shábháil';
$string['cannotsavezipfile'] = 'Ni féidir an comhad ZIP a shábháil';
$string['cannotunzipfile'] = 'Ní féidir an comhad a dhízipeáil';
$string['componentisuptodate'] = 'Tá an chomhpháirt suas chun dáta';
$string['downloadedfilecheckfailed'] = 'Theip ar an seiceáil comhaid íoslódailte';
$string['invalidmd5'] = 'Bhí "an athróg seiceála mícheart – triail arís é';
$string['missingrequiredfield'] = 'Réimse riachtanach ar iarraidh';
$string['remotedownloaderror'] = 'Theip ar íoslódail comhpháirte chuig do fhreastalaí, dearbhaigh seachshocruithe moltar iarmhíreanna , PHP cURL go hard.<br /"><br />Y Caithfidh tú an comhad <a href="""{$a->url}"">{$a->url}</a> a íoslódáil de láimh';
$string['wrongdestpath'] = 'Cosán sprice mícheart';
$string['wrongsourcebase'] = 'Foinse mícheart do bhunachar URL';
$string['wrongzipfilename'] = 'Ainm mícherat comhaid ZIP';
