<?php



/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link http://docs.lion.org/dev/Languages/AMOS}) using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package    install
 * @subpackage lang
 * @copyright  2015 Pooya Saeedi
 */

defined('LION_INTERNAL') || die();

$string['clianswerno'] = 'n';
$string['cliansweryes'] = 'y';
$string['cliincorrectvalueerror'] = 'ত্রুটি, "{$a->option}"-র জন্য "{$a->value}" ভুল মান ';
$string['cliincorrectvalueretry'] = 'ভুল মান, অনুগ্রহ করে আবার চেষ্টা করুন';
$string['clitypevalue'] = 'ধরনের মান';
$string['clitypevaluedefault'] = 'ধরনের মান, পূর্বনির্ধারিত মান ({$a}) ব্যবহার করতে এন্টার (Enter) চাপুন';
$string['cliunknowoption'] = 'অচেনা অপশন:
  {$a}
অনুগ্রহ করে --সহায়তা অপশন ব্যবহার করুন।';
$string['cliyesnoprompt'] = 'y (মানে হ্যাঁ) বা n (মানে না) টাইপ করুন';
$string['environmentrequireinstall'] = 'অবশ্যই ইনস্টল ও সক্রিয় করতে হবে';
$string['environmentrequireversion'] = '{$a->needed} সংস্করণ আবশ্যক এবং আপনি {$a->current} চালাচ্ছেন';
