<?php


/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically  using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * 
 */

defined('LION_INTERNAL') || die();

$string['cannotcreatelangdir'] = 'भाषेची फोल्डर तयार करु शकत नाही';
$string['cannotcreatetempdir'] = 'टेम्प फोल्डर तयार करु शकत नाही';
$string['cannotdownloadcomponents'] = 'भाग डाउंनलोड करु शकत नाही';
$string['cannotdownloadzipfile'] = 'ZIP फाईल डाउडलोड करु शकत नाही';
$string['cannotfindcomponent'] = 'भाग सापडत नाही';
$string['cannotsavemd5file'] = 'एमडी5 साठवु शकत नाही';
$string['cannotsavezipfile'] = 'ZIP फाईल साठवु शकत नाही';
$string['cannotunzipfile'] = 'ZIP फाईल UNZIP करु शकत नाही';
$string['componentisuptodate'] = 'भागहे सध्याच्या दिनांकापर्यत दुरूस्त आहे';
$string['downloadedfilecheckfailed'] = 'डाउंनलोड फाईल चुकीची आहे ती बरोबर बघा';
$string['invalidmd5'] = 'एमडी5 अमान्य आहे';
$string['missingrequiredfield'] = 'अपेक्षित क्षेत्रची माहिती नाही';
$string['wrongdestpath'] = 'फाईलचा पाथ अमान्य आहे';
$string['wrongsourcebase'] = 'युआरएल माहिती अमान्य आहे';
$string['wrongzipfilename'] = 'झिप फाईल अमान्य आहे';
