<?php


/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link http://docs.lion.org/dev/Languages/AMOS}) using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * 
 */

defined('LION_INTERNAL') || die();

$string['admindirname'] = 'व्यवस्थापकाची डिरेक्टरी';
$string['availablelangs'] = 'उपलब्ध भाषा संच';
$string['chooselanguagehead'] = 'भाषा निवडा';
$string['chooselanguagesub'] = 'क्रुपया फक्त इंस्टॉलेशनसाठी भाषा निवडा. तुम्ही नंतरच्या पानावरती साइट आणि युजरसाठी भाषा निवडू शकाल';
$string['dataroot'] = 'माहीतीची डिरेक्टरी';
$string['dbprefix'] = 'टेबलचे आद्याक्षर';
$string['dirroot'] = 'मूडलची डिरेक्टरी';
$string['environmenthead'] = 'तुमचे पर्यावरण तपासत आहे';
$string['installation'] = 'इंस्टॉलेशन';
$string['phpversion'] = 'PHP ची प्रत';
$string['welcomep60'] = 'खालील पानामध्ये तुम्हाला तुमच्या संगणकावरती मूडल सेट व कॉनफिगर करण्यासाठी काही सोप्या पद्धती दिलेल्या आहेत. तुम्ही डिफॉल्ट सेटींग ठेवू शकता किंवा  तुम्हाला हव्या त्या सुधारणा करू शकता.';
$string['welcomep70'] = 'मूडलचा सेट अप चालू ठेवण्यासाठी \'पूढे\' या बटनवरती क्लिक करा.';
$string['wwwroot'] = 'वेबचा पत्ता';
