<?php


/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link http://docs.lion.org/dev/Languages/AMOS}) using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * 
 */

defined('LION_INTERNAL') || die();

$string['cannotcreatelangdir'] = 'Negalima sukurti kalbos katalogo';
$string['cannotcreatetempdir'] = 'Negalima sukurti laikinojo katalogo';
$string['cannotdownloadcomponents'] = 'Negalima atsisiųsti komponentų';
$string['cannotdownloadzipfile'] = 'Negalima atsisiųsti ZIP failo';
$string['cannotfindcomponent'] = 'Nepavyko rasti komponento';
$string['cannotsavemd5file'] = 'Negalima įrašyti md5 failo';
$string['cannotsavezipfile'] = 'Negalima įrašyti ZIP failo';
$string['cannotunzipfile'] = 'Negalima išskleisti failo';
$string['componentisuptodate'] = 'Komponentas atnaujintas';
$string['downloadedfilecheckfailed'] = 'Nepavyko patikrinti atsisiųsto failo';
$string['invalidmd5'] = 'Kintamojo patikra nepavyko – bandykite dar kartą';
$string['missingrequiredfield'] = 'Trūksta būtino lauko';
$string['remotedownloaderror'] = 'Nepavyko į serverį atsisiųsti komponento, patikrinkite tarpinio serverio parametrus, labai rekomenduojama naudoti PHP cURL plėtinį.<br /><br />Turite rankiniu būdu atsisiųsti <a href="{$a->url}">{$a->url}</a> failą, nukopijuoti jį į {$a->dest} serveryje ir ten jį išskleisti.';
$string['wrongdestpath'] = 'Neteisingas paskirties kelias';
$string['wrongsourcebase'] = 'Neteisingas šaltinio URL pagrindas';
$string['wrongzipfilename'] = 'Neteisingas ZIP failo vardas';
