<?php



/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link http://docs.lion.org/dev/Languages/AMOS}) using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package    install
 * @subpackage lang
 * @copyright  2015 Pooya Saeedi
 */

defined('LION_INTERNAL') || die();

$string['cannotcreatelangdir'] = 'មិនអាចបង្កើតថត lang បានឡើយ ។';
$string['cannotcreatetempdir'] = 'មិនអាចបង្កើតថត temp បានឡើយ ។';
$string['cannotdownloadcomponents'] = 'មិនអាចទាញយកសមាសភាគបានឡើយ ។';
$string['cannotdownloadzipfile'] = 'មិនអាចទាញយកឯកសារ ZIP បានឡើយ ។';
$string['cannotfindcomponent'] = 'មិនអាចរកសមាភាគបានឡើយ ។';
$string['cannotsavemd5file'] = 'មិនអាចរក្សាទុកឯកសារ md5 បានឡើយ ។';
$string['cannotsavezipfile'] = 'មិនអាចរក្សាទុកឯកសារ ZIP បានឡើយ ។';
$string['cannotunzipfile'] = 'មិនអាចពន្លាឯកសារបានឡើយ ។';
$string['componentisuptodate'] = 'សមាសភាគគឺទាន់សម័យ ។';
$string['downloadedfilecheckfailed'] = 'បានបរាជ័យក្នុងការពិនិត្យឯកសារដែលបានទាញយក ។';
$string['invalidmd5'] = 'md5 មិនត្រឹមត្រូវ';
$string['missingrequiredfield'] = 'បាត់វាលដែលត្រូវការមួយចំនួន';
$string['remotedownloaderror'] = 'បរាជ័យក្នុងការទាញយកសមាសភាគទៅម៉ាស៊ីនបម្រើរបស់អ្នក សូមផ្ទៀងផ្ទាត់ប្រូកស៊ី ផ្នែកបន្ថែម PHP cURL ត្រូវបានផ្ដល់អនុសាសន៍ ។<br /><br />អ្នកត្រូវតែទាញយកឯកសារ <a href="{$a->url}">{$a->url}</a> ដោយដៃ ចម្លងវាទៅ "{$a->dest}" ក្នុងម៉ាស៊ីនបម្រើរបស់អ្នក និងពន្លាវានៅទីនោះ ។';
$string['wrongdestpath'] = 'ផ្លូវទិសដៅមិនត្រឹមត្រូវ ។';
$string['wrongsourcebase'] = 'មូលដ្ឋាន URL ប្រភពមិនត្រឹមត្រូវ ។';
$string['wrongzipfilename'] = 'ឈ្មោះឯកសារ ZIP មិនត្រឹមត្រូវ ។';
