<?php


/**
 * Automatically generated strings for Lion installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically  using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * 
 */

defined('LION_INTERNAL') || die();

$string['clianswerno'] = 't';
$string['cliansweryes'] = 'y';
$string['cliincorrectvalueerror'] = 'Ralat, nilai tidak betul "{$a->value}" untuk "{$a->option}"';
$string['cliincorrectvalueretry'] = 'Nilai yang salah, sila cuba lagi';
$string['clitypevalue'] = 'taip nilai';
$string['clitypevaluedefault'] = 'taip nilai, tekan Enter untuk gunakan nilai lalai ({$a})';
$string['cliunknowoption'] = 'Pilihan yang tidak diketahui:
  {$a}
Sila gunakan pilihan --help';
$string['cliyesnoprompt'] = 'tapi y (ya) atau t (tidak)';
